### ISSUE TITLE
Q: What is purpose of models.yaml?

### ISSUE THREAD

**Issue by vt-alt** [sigoden/aichat#1011]
Can you please explain what is the purpose of `models.yaml` file?
For example, why it's only 6 models and not all 58 [models](https://github.com/sigoden/aichat/issues/1000) they provide?

Also, https://build.nvidia.com/nim provides some models (including their latest llama-3.1-nemotron-70b-instruct) with free 1000 requests quota, but it's not listed there. I meant, while pull requests are not encouraged, should we suggest other provides for inclusion?

**Comment by sigoden** [comment]
In the AI chat, a client has a 'models' field that defines the models that the client provides.

```yaml
  - type: openai-compatible
    name: ..
    api_base: ..
    models:
    - name: gpt-4o
      max_input_tokens: 128000
      max_output_tokens: 16384
      input_price: 2.5
      output_price: 10
      supports_vision: true
      supports_function_calling: true
      ...
```
We extract the models and put them into models.yaml, so the user doesn't need to manually maintain them.

Each client/provider has many models, including outdated and deprecated ones, aichat will select the best options from it.

There are too many LLM providers; it's impossible to include them all. There are mainly two categories.
- Has its own models，such as openai, claude, gemini, deepseek..
- Host a lot mainstream models, such as groq, together, ollama...


The `navidia nim` not include because it not a production-ready provider. The free 1000 request quota runs out quickly, and there's no way to top it up directly.

> Although aichat does not directly support `nvidia-nim`, users can add their own configuration.
