### ISSUE TITLE
Proxy for localhost is impossible to turn off

### ISSUE THREAD

**Issue by vt-alt** [sigoden/aichat#1013]
**Describe the bug**
When proxy is configured via env such as
```
NO_PROXY=127.0.0.1,localhost,10.0.0.0/8,192.168.0.0/16
ALL_PROXY=socks5h://127.0.0.1:1080
```
aichat tries to connect to ollama on localhost via proxy, and fails.
Even if client is configured with `proxy: null` it still tries to connect via proxy and fails.

So it will be nice if proxy would be configurable to be not used for some client or for localhost (and intranet, perhaps).

**Screenshots/Logs**
```
$ aichat -m ollama:codellama:code
Welcome to aichat 0.24.0
Type ".help" for additional help.
> qwe
Error: Failed to call chat-completions api

Caused by:
    error sending request for url (http://localhost:11434/v1/chat/completions)

>
```

**Environment (please complete the following information):**
- os version: ALT Linux
- aichat version: 0.24.0

**Comment by 5HT2** [comment]
Where are you getting `NO_PROXY` from? This is not defined anywhere.

Just set it to nothing or a `-`.

https://github.com/sigoden/aichat/blob/6f60ad47535b75064a79331c22758d86e6e46d4f/src/utils/mod.rs#L214-L226

**Comment by vt-alt** [comment]
Proxy configuration is not highly standardized. But obviously localhost should not be proxied, as this will quickly make global (per user) proxy support via env unusable. `NO_PROXY` is supported by curl.

Yes I saw that code and tried '-' but it didn't work.

My config:
```
- type: openai-compatible
  name: ollama
  api_base: http://localhost:11434/v1
  proxy: '-'
  models:
    - name: codellama:code
```
```
$ aichat -m ollama:codellama:code hello
Error: Failed to call chat-completions api

Caused by:
    error sending request for url (http://localhost:11434/v1/chat/completions)
$ unset ALL_PROXY HTTP_PROXY HTTPS_PROXY
$ aichat -m ollama:codellama:code hello
World(String)....
```

Also, it seems `reqwest` supports `NO_PROXY`: https://github.com/seanmonstar/reqwest/blob/master/src/proxy.rs#L452
So this isn't like unheard of.

**Comment by sigoden** [comment]
@vt-alt 

#1015 solved the problem.

But in aichat v0.24.0, you can use `extra.proxy: '-'` to make it work.
```
- type: openai-compatible
  name: ollama
  api_base: http://localhost:11434/v1
  extra:
    proxy: '-'
```
