### ISSUE TITLE
Error when exec aichat.exe

### ISSUE THREAD

**Issue by lbarasc** [sigoden/aichat#1029]
Under windows 10 x64, with latest Ollama,
on command consol when i type "aichat.exe" + ENTER, i have this message : 

Error: Unknown chat model 'ollama'

**Comment by sigoden** [comment]
Your configuration is incorrect.

There are two ways to handle it. All need to edit `<aichat-config-dir>/config.yaml`

**1. Change model**

Update `model` field 
```diff
-model: ollama
+model: <any-valid-model>  # such as `openai:gpt-4o`
```

**2. Add ollama client**

Please add following client configuration
```
clients:
  - type: openai-compatible
    name: ollama
    api_base: http://127.0.0.1:11434/v1
```

**Comment by rbutera** [comment]
@sigoden i'm facing this issue as well even with this minimal config file:

```yaml
# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: openai:gpt-4o
# clients:
# - type: claude
#   api_key: null
# prelude: role:navi-4o

```

**Comment by fanpei91** [comment]
``` yaml
model: ollama:llama3.2 # see https://github.com/ollama/ollama?tab=readme-ov-file#model-library
clients:
- type: openai-compatible
  name: ollama
  api_base: http://localhost:11434/v1
  api_key: null
```

It works.
