### ISSUE TITLE
How to use GitHub copilot?

### ISSUE THREAD

**Issue by wakuflair** [sigoden/aichat#1030]
This may be a dumb question, but I don't find a way to use GitHub copilot. 

To be honest, I even can't find copilot's key.

It'd better that aichat pops up a browser page of GitHub authentication and config it automatically.

**Comment by sigoden** [comment]
AIChat does not support GitHub Copilot because Copilot does not officially provide any API.

Maybe you can try [GitHub Models](https://github.com/marketplace/models).

**Comment by ktunprasert** [comment]
@sigoden 
Sorry to bring this back up but I think they do provide chat functionality now - the API is undocumented but I've been using [avante.nvim](https://github.com/yetone/avante.nvim) with copilot chat + different available models

```
➜ xhs api.githubcopilot.com/models -Abearer -a (gh auth token) | jq '.data | .[] | .id'
"gpt-3.5-turbo"
"gpt-3.5-turbo-0613"
"gpt-4o-mini"
"gpt-4o-mini-2024-07-18"
"gpt-4"
"gpt-4-0613"
"gpt-4o"
"gpt-4o-2024-05-13"
"gpt-4-o-preview"
"gpt-4o-2024-08-06"
"gpt-4o-2024-11-20"
"text-embedding-ada-002"
"text-embedding-3-small"
"text-embedding-3-small-inference"
"gemini-2.0-flash-001"
```

**Comment by Zhaoyilunnn** [comment]
> [@sigoden](https://github.com/sigoden) Sorry to bring this back up but I think they do provide chat functionality now - the API is undocumented but I've been using [avante.nvim](https://github.com/yetone/avante.nvim) with copilot chat + different available models
> 
> ```
> ➜ xhs api.githubcopilot.com/models -Abearer -a (gh auth token) | jq '.data | .[] | .id'
> "gpt-3.5-turbo"
> "gpt-3.5-turbo-0613"
> "gpt-4o-mini"
> "gpt-4o-mini-2024-07-18"
> "gpt-4"
> "gpt-4-0613"
> "gpt-4o"
> "gpt-4o-2024-05-13"
> "gpt-4-o-preview"
> "gpt-4o-2024-08-06"
> "gpt-4o-2024-11-20"
> "text-embedding-ada-002"
> "text-embedding-3-small"
> "text-embedding-3-small-inference"
> "gemini-2.0-flash-001"
> ```
> 
> edit: Apologies, it seems like you have the "github" provider while I was looking for "copilot" please ignore
> 
> edit2: I got the configuration to work
> 
> # see https://github.com/sigoden/aichat/blob/main/config.example.yaml
> stream: false
> model: copilot:claude-3.5-sonnet
> clients:
> - type: openai-compatible
>   name: copilot
>   api_key: 'xxx' # exchange your `ghu_` token at https://api.github.com/copilot_internal/v2/token with Bearer token
>   api_base: https://api.githubcopilot.com
>   patch:                                          # Patch api
>     chat_completions:                             # Api type, possible values: chat_completions, embeddings, and rerank
>       '.*':                                    # The regex to match model names, e.g. '.*' 'gpt-4o' 'gpt-4o|gpt-4-.*'
>         headers:                                  # Patch request headers
>           Copilot-Integration-Id: vscode-chat
>           Editor-Version: aichat/0.1.0 # optional

Hi, thanks a lot for providing this example, my config is 

```
# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

stream: false
model: copilot:gpt-4.1
clients:
  - type: openai-compatible
    name: copilot
    api_base: https://api.githubcopilot.com
    api_key: ghu_xxxx
    patch: # Patch api
    chat_completions: # Api type, possible values: chat_completions, embeddings, and rerank
      ".*": # The regex to match model names, e.g. '.*' 'gpt-4o' 'gpt-4o|gpt-4-.*'
        headers: # Patch request headers
          Copilot-Integration-Id: vscode-chat
          Editor-Version: aichat/0.1.0 # optional
```

But I got

```
Welcome to aichat 0.30.0
Type ".help" for additional help.
> hi
Error: Failed to call chat-completions api

Caused by:
    0: error decoding response body
    1: expected value at line 1 column 1
```

Any idea on this ...

**Comment by ktunprasert** [comment]
> Hi, thanks a lot for providing this example, my config is
> 
> ```
> # see https://github.com/sigoden/aichat/blob/main/config.example.yaml
> 
> stream: false
> model: copilot:gpt-4.1
> clients:
>   - type: openai-compatible
>     name: copilot
>     api_base: https://api.githubcopilot.com
>     api_key: ghu_xxxx
>     patch: # Patch api
>     chat_completions: # Api type, possible values: chat_completions, embeddings, and rerank
>       ".*": # The regex to match model names, e.g. '.*' 'gpt-4o' 'gpt-4o|gpt-4-.*'
>         headers: # Patch request headers
>           Copilot-Integration-Id: vscode-chat
>           Editor-Version: aichat/0.1.0 # optional
> ```
> 
> But I got
> 
> ```
> Welcome to aichat 0.30.0
> Type ".help" for additional help.
> > hi
> Error: Failed to call chat-completions api
> 
> Caused by:
>     0: error decoding response body
>     1: expected value at line 1 column 1
> ```
> 
> Any idea on this ...

Your `ghu_` token must be exchanged as per the comment, the bearer token must be in the format of `tid=....;exp=....;....`
They expire pretty quick so you have to keep exchanging it. Luckily `aichat` is pretty versatile so all you need to do is populate the environment variable `COPILOT_API_KEY` which will be used instead of the `api_key:` there

Putting this together you have:
```yaml
model: copilot:gpt-4.1
clients:
  - type: openai-compatible
    name: copilot
    api_base: https://api.githubcopilot.com
    # no more api_key
    patch: # Patch api
      chat_completions: # Api type, possible values: chat_completions, embeddings, and rerank
        ".*": # The regex to match model names, e.g. '.*' 'gpt-4o' 'gpt-4o|gpt-4-.*'
          headers: # Patch request headers
            Copilot-Integration-Id: vscode-chat
            Editor-Version: aichat/0.1.0
```

Here's my fish script setup just use AI to translate it to your shell
```fish
#~/.config/fish/functions/aic.fish
# check if $COPILOT_API_KEY is set
# if it does run # check if $COPILOT_API_KEY is aichat $args
# otherwise run `load_copilot_key` then run `aichat`
# supports --silent flag to suppress the echo message from load_copilot_key
function aic
    # Check if --silent flag is present
    set -l silent_mode false
    set -l new_argv

    for arg in $argv
        if test "$arg" = "--silent"
            set silent_mode true
        else
            set -a new_argv $arg
        end
    end

    # Check if key is not set or if it has expired
    set -l need_refresh false

    if test -z "$COPILOT_API_KEY"
        set need_refresh true
    else
        # Extract expiration time from token and check if expired
        set -l current_time (date +%s)

        # Try to extract expiration from token (assumes token contains "exp=TIMESTAMP")
        set -l exp_string (echo $COPILOT_API_KEY | grep -o "exp=[0-9]*" | head -n 1)

        if test -n "$exp_string"
            set -l exp_time (echo $exp_string | cut -d= -f2)
            if test "$current_time" -ge "$exp_time"
                # Token has expired
                set need_refresh true
            end
        end
    end

    if test "$need_refresh" = true
        # Key is not set or has expired, so load a fresh one
        if test "$silent_mode" = true
            load_copilot_key --silent
        else
            load_copilot_key
        end
    end

    # Run aichat with arguments
    aichat $new_argv
end
```
```fish
# ~/.config/fish/functions/load_copilot_key.fish
# Load GitHub Copilot API key from hosts.json file
function load_copilot_key
    # Check for silent flag
    set -l silent false
    for arg in $argv
        if test "$arg" = "--silent"
            set silent true
        end
    end

    # Extract the OAuth token from GitHub Copilot hosts file
    set -l OAUTH_TOKEN (bat ~/.config/github-copilot/hosts.json | jq '."github.com".oauth_token' -r)

    set -gx COPILOT_API_KEY (xhs api.github.com/copilot_internal/v2/token -Abearer -a $OAUTH_TOKEN | jq .token -r)

    # Print token for confirmation unless silent mode is enabled
    if test "$silent" = false
        echo "Token set at COPILOT_API_KEY"
    end
end
```

https://github.com/user-attachments/assets/b08a531b-5750-4f6a-82db-fab0ddf3a18e
