### ISSUE TITLE
Sambanova AI support

### ISSUE THREAD

**Issue by supagu** [sigoden/aichat#1058]
Can we get support for Sambanova?

https://cloud.sambanova.ai/

Or at least a sample of how I might set it up?

**Comment by sigoden** [comment]
```
> .rag aichat-wiki

@aichat-wiki> how to add openai compatible client
To add an OpenAI-compatible client, you can use the following configuration structure in your YAML configuration file:

```yaml
clients:
  - type: openai-compatible
    name: <client-name>     # Replace with desired client name
    api_base: <api-url>     # Replace with the API base URL
    api_key: <api-key>      # Optional: provide API key if required
    models:
      - name: <model-name>   # Replace with the model name
        max_input_tokens: <max-tokens>  # Set the maximum input tokens for the model
        supports_function_calling: <true/false>  # Set whether it supports function calling or not
```

For example, here's how to add a local OpenAI-compatible client:

```yaml
clients:
  - type: openai-compatible
    name: local
    api_base: http://localhost:8080/v1
    api_key: xxx  # Optional
    models:
      - name: llama3.1
        max_input_tokens: 128000
        supports_function_calling: true
      - name: jina-embeddings-v2-base-en
        type: embedding
        default_chunk_size: 1500
        max_batch_size: 100
      - name: jina-reranker-v2-base-multilingual
        type: reranker
```

Replace the placeholders with your specific settings and models. Make sure to refer to any configuration examples for further details on the parameters.
```
