### ISSUE TITLE
Support custom REPL commands

### ISSUE THREAD

**Issue by sigoden** [sigoden/aichat#1077]
The current REPL mode provides a great interactive experience, but adding support for custom REPL commands would greatly enhance its usability and flexibility. Users could create shortcuts for repetitive tasks or commands that are specific to their workflow, making the tool even more powerful and user-friendly.

## Proposal

Macros are defined using YAML files located in the `<aichat-config-dir>/macros/` directory. Each file represents a single macro. The filename (without the `.yaml` extension) becomes the macro's name.

Here's a breakdown of the YAML structure:

- **`variables`**: (Optional) An array of variable definitions.
- **`steps`**: (Required) An array of strings, where each string represents a single REPL command to be executed sequentially. These commands should be valid REPL commands.

**Variable Definition Structure:**

  - **`name`**: (Required) The name of the variable used within the macro steps using `{{name}}` syntax.
  - **`default`**: (Optional) A default value for the variable. If a value isn't provided during execution, the default will be used. An error occurs if a variable lacks a default and no value is provided.
  - **`rest`**: (Optional, Boolean) Set to `true` to collect remaining arguments into a single variable (applicable only to the last variable). Default is `false`.

**Example Macro Configurations:**

```yaml
# <aichat-config-dir>/macros/generate-commit-message.yaml
steps:
  - .file `git diff` -- generate git commit message
```

```yaml
# <aichat-config-dir>/macros/within-agent.yaml
variables:
  - name: agent
  - name: args
    rest: true
    default: What can your do?
steps:
  - .agent {{agent}}
  - '{{args}}'
```

```yaml
# <aichat-config-dir>/macros/multi-agents.yaml
variables:
  - name: args
    rest: true
steps:
  - .agent design-tui
  - '{{args}}'
  - .agent build-tui
  - .file %%
  - .agent fixing-bugs
  - .file %%
```

### New `.macro` REPL Command

Add a new REPL command `.macro` to execute the macro. The syntax would be as follows:

```
.macro <customp-repl-command> <args>...

> .macro generate-commit-message
> .macro within-agent todo
> .macro within-agent todo list all my todos
```

The `.macro` also supports creating a new macro if it does not exist.

```
> .macro test
? Create a new macro? (Y/n)  
```

### New CLI Options: `--macro` and `--list-macros`

Add a `--macro` CLI option to execute custom macros directly from the command line:

```
aichat --macro generate-commit-message
aichat --macro test-function-calling
```

Aadd a `--list-macros` CLI option to list all avaiables macros:

```
aichat --list-macros
```

## Requirements

- **Macro Naming**: Macro names must consist of a single phrase (no spaces).
- **Valid REPL Commands**: All repl commands defined in `steps` must be valid REPL commands.
- **Isolated Context Execution**: The AIChat will create an isolated context for executing macro, ensuring:
  - No pre-existing role/session/rag/agent state is carried over.
  - The current context remains unaffected.
