### ISSUE TITLE
Suggestion for `roles_file structure` to classify items

### ISSUE THREAD

**Issue by Yang-Kyle** [sigoden/aichat#111]
Here's an example of the structure I'm suggesting !
> It could make it more organized and easier to manage, more flexible and extendable.
```yml
- category: game
  item
    - name: escape
      prompt: balabala 00
      temperature: null
    - name: logue
      prompt: balabala 01
      temperature: null
- category: emulator
  item
    - name: advanture
      prompt: balabala 02
      temperature: null
    - name: linux
      prompt: balabala 03
      temperature: null
```
 Allowing for easy **expansion and customization** in the future.
