### ISSUE TITLE
support kluster.ai

### ISSUE THREAD

**Issue by brentp** [sigoden/aichat#1125]
thanks for the great tool!

**Is your feature request related to a problem? Please describe.**

kluster.ai supports many models (including deepseek-r1 and has $100 free credit), it would be nice to support this.

(also, I added hyperbolic.xyz to my config.yaml, but it's not showing under models)

**Comment by sigoden** [comment]
AIChat already supports OpenAI-compatible LLM providers.

The models.yaml is for mainstream or well-known LLM providers, kluster.ai is not yet qualified to be included.

hyperbolic.xyz has been added in v0.27.0, which has not been released yet.

**Comment by brentp** [comment]
Thanks. I didn't see docs on how to do this but managed the following which seems to work
```
- type: openai-compatible
  name: kluster
  api_base: https://api.kluster.ai/v1/
  api_key: $key
  models:
    - name: deepseek-ai/DeepSeek-R1
      max_input_tokens: 131072
      max_output_tokens: 16384
      input_price: 2
      output_price: 2
    - name: klusterai/Meta-Llama-3.3-70B-Instruct-Turbo
      max_input_tokens: 131072
      max_output_tokens: 8192
```
to config.yaml.
