### ISSUE TITLE
Verbose request output or log files

### ISSUE THREAD

**Issue by TheCodeLamp** [sigoden/aichat#1136]
Is there any way of displaying a more verbose output, or to view log files?

I'm using ollama as a backend and want to use [this](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately) to shorten the length the model is kept in memory.
I've edited the aichat config file to add this patch to the ollama client:
```
clients:
  - type: openai-compatible
    name: ollama
    api_base: http://localhost:11434/v1
    patch:
      chat_completions:
        '.*':
          body:
            "keep_alive": "0"
```
But it doesn't seem to work. I've tried it with curl and observed that this variable works if it is sent in the data field.
I've tried using `keep_alive: 0` and `keep_alive: "0"` but nothing works.

Is there a way to see the packets that aichat is sending or do I need to download wireshark?
