### ISSUE TITLE
Managing Incompatibilities in the OpenAI-Compatible API: Changes to `max_completion_tokens` and the `developer` Role

### ISSUE THREAD

**Issue by sigoden** [sigoden/aichat#1146]
## Overview

OpenAI's introduction of the `o*` series models, like `o1`, `o1-mini`, and `o3-mini`, brought with it some significant changes to the /chat/completions API:

1. The transition from `max_tokens` to `max_completion_tokens`.
2. The alteration in the system role type from `system` to `developer`.

These updates have not been popular among many Language Model (LLM) providers as they maintain OpenAI-compatible APIs but do not incorporate these changes. 

These providers offer OpenAI-compatible APIs but do not adopt such changes.

Notably, some providers have adapted to these changes:
- Groq reasoning models
- GitHub's `o*` models, although it's unclear why `deepseek-r1` has not adopted these changes.

This situation has caused significant confusion, and AIChat needs a strategy to navigate this issue.

## Solution 1: Add new fields to the model definition

```yaml
  - type: openai-compatible
    name: github
    models:
      - name: o3-mini
        supports_max_completion_tokens: true
        supports_developer_role: true
```

## Solution 2: Use new fields to the client configuration

```yaml
  - type: openai-compatible
    name: github
    use_max_completion_tokens_models: o.*
    use_developer_role_models: o.*

  - type: openai-compatible
    name: github
    use_max_completion_tokens_models: reasoning
    use_developer_role_models: reasoning
```

Possible values for `use_***_models`:
  - `all` for all models
  - `reasoning` for reasoning models
  - regex for match model names

## Conclusion

Which solution do you think is better? Or do you have another solution? We welcome your ideas and feedback.
