### ISSUE TITLE
Introduce the alias for the models

### ISSUE THREAD

**Issue by qcts33** [sigoden/aichat#1147]
**Is your feature request related to a problem? Please describe.**

The volcengine (bytedance) platform is using the [endpoint ID](https://www.volcengine.com/docs/82379/1099522) as the model name in their [openai API](https://www.volcengine.com/docs/82379/1330626), so the model name is difficult to remember.

**Describe the solution you'd like**

Introduce the alias for the models, so the config file is like:
```yaml
  - type: openai-compatible
    name: volce
    api_base: https://ark.cn-beijing.volces.com/api/v3
    api_key: xxx
    models:
      - name: ep-xxxx-yyyy
        alias: deepseek-v3
      - name: ep-aaaa-bbbb
        alias: doubao-1.5-pro
```
And the model could be referenced like `volce:doubao-1.5-pro`

**Describe alternatives you've considered**

**Additional context**
