### ISSUE TITLE
Claude + VoyageAI RAG config "The client doesn't support embeddings api"

### ISSUE THREAD

**Issue by colinmollenhour** [sigoden/aichat#1154]
I'm not sure if this is an unsupported combination or I'm doing something else wrong in the config.

Here is my config:
```
model: claude
clients:
- type: claude
  name: claude
  api_key: sk-ant-api03---.....
  models:
    - name: claude
    - name: voyage-3-lite
      type: embedding
      max_input_tokens: 32000

- type: openai-compatible
  name: voyage-3-lite
  api_base: https://api.voyageai.com/v1
  api_key: pa-.....
```

Then I run `.rag`:
```
> .rag ss-test
⚙ Initializing RAG...
> Select embedding model: claude:voyage-3-lite (max-tokens:-;max-batch:-;price:-)
> Set chunk size: 1000
> Set chunk overlay: 50
> Add documents: https://example.com/....
Load https://example.com/....
Error: Failed to create embedding after 2 attempts

Caused by:
    0: Failed to call embeddings api
    1: The client doesn't support embeddings api
```

I've never written Rust before, had to read through the code to get this far.. It wasn't clear that the Voyage API key needed to be in the clients with a name matching the models. Still not sure what I'm missing though.

I also tried this:
```
model: claude:claude-3-5-sonnet-20241022
clients:
- type: claude
  name: claude
  api_key: sk-ant-api03---....
  models:
    - name: voyage-3-lite
      type: embedding
      default_chunk_size: 1500
      max_batch_size: 100
      max_input_tokens: 32000

- type: voyageai
  name: voyage-3-lite
  api_base: https://api.voyageai.com/v1
  api_key: pa-....
```

But with this I can't even chat, I get:

```
Error: Failed to call chat-completions api

Caused by:
    max_tokens: Field required (type: invalid_request_error)
```

Any advice? TIA!

**Comment by sigoden** [comment]
Claude does not support any embedded models.

We have predefined models in [models.yaml](https://github.com/sigoden/aichat/blob/main/models.yaml), why are you manually adding wrong models to each client?

Please fix your client configuration as follows.
```
clients:
  - type: claude
    api_key: sk-xx
  - type: openai-compatible
    name: voyageai
    api_key: pa-xxx
```

Then select embedding model `voyageai:voyage-3-lite`

**Comment by colinmollenhour** [comment]
Claude does not have its own embedding model and the [official docs](https://docs.anthropic.com/en/docs/build-with-claude/embeddings#how-to-get-embeddings-with-anthropic) suggest using Voyage. Voyage does not have it's own LLM, it's just an embedding model, so I thought this was a reasonable approach, but I don't understand the inner workings of aichat codebase. However, if this is not a valid combination, then what was the point of adding the `voyageai` provider in #645?

Using this minimal config example as you suggested:
```
model: claude:claude-3-5-sonnet-20241022
rag_embedding_model: voyageai:voyage-3-lite
clients:
- type: claude
  api_key: sk-ant-api03---....
- type: openapi-compatible
  name: voyageai
  api_key: pa-....
```
I get this error:
```
❯ aichat
Welcome to aichat 0.27.0
Type ".help" for additional help.
> Hello
Hi! How can I help you today?

> .rag test
⚙ Initializing RAG...
Select embedding model: voyageai:voyage-3-lite
Error: Unknown embedding model 'voyageai:voyage-3-lite'
```
