### ISSUE TITLE
Support fallback between API providers

### ISSUE THREAD

**Issue by qcts33** [sigoden/aichat#1183]
**Is your feature request related to a problem? Please describe.**

Due to the popularity of deepseek models, many service providers are unable to guarantee the reliability of their API services, and manually switching service providers is time consuming and labour intensive.

**Describe the solution you'd like**

Provides load balancing and fallback between service providers.
The user can define a route group, when the user calls this group, aichat will call the models defined in the group in order or randomly, if the call times out or returns an error, aichat can try to select the next model to call.
For example, user can add a config like this:
```yaml
groups:
  - name: deepseek-v3
    type: fallback # "fallback" calls the models in order, "balance" calls the models randomly
    models:
      - deepseek:deepseek-chat
      - siliconflow:deepseek-ai/DeepSeek-V3
      - ppinfra:deepseek/deepseek-v3/community
```
Than, the user can invoke aichat like `aichat -m deepseek-v3`, aichat will try `deepseek:deepseek-chat` first, and when it results in an timeout, aichat will try to call  `siliconflow:deepseek-ai/DeepSeek-V3`.

**Describe alternatives you've considered**

It is possible to rely on external tools for fallback, and since aichat does not have direct access to the service status of the provider, it is difficult to set a reasonable timeout.

**Additional context**

Load balancing designs can be very complex, but I think we should avoid using external databases to hold service provider availability information, and provide two simple load balancing policies of fallback in a given order or random order is sufficient.
