### ISSUE TITLE
How can an old user fetch models for Hyperbolic/Fireworks using a pre-existing configuration file?

### ISSUE THREAD

**Issue by milanglacier** [sigoden/aichat#1188]
I recently upgraded to `v0.28.0`, and I've noticed that starting with update #1161, OpenAI-compatible models are now fetched from remote sources rather than being predefined in the `models.yaml`. According to #1161, models should be retrieved during configuration initialization. However, as a long-time user with an existing configuration file, I will not go through this initialization process.

I also attempted to use `aichat --sync-models`, but I didn't see any fireworks models reflected in the `models-override.yaml`.

Is there something I might be overlooking?

Here's my example configuration:

```yaml

light_theme: false
model: openai:gpt-4o
save_session: false # don't ask whether save session when quit.
compress_threshold: 0 # don't compress session for long conversation.

clients:
  - type: openai
  - type: openai-compatible
    name: fireworks
    api_base: https://api.fireworks.ai/inference/v1
    api_key: xxxxx
```

Additionally, in aichat sessions, using `.models <tab>` doesn't provide model completions for the fireworks configuration.
