### ISSUE TITLE
Tool and Agent Integration in chatai

### ISSUE THREAD

**Issue by blankjul** [sigoden/aichat#1221]
I really like this framework and could not stop using it over the last week! Thanks for building and maintaining it! I would love to discuss the tools and agent creation in this issue.

**Context**

Adding tools brings a lot of power to `aichat` and I think is very fundamental. With the more and more popular `Model Context Protocol (MCP)` we finally have a common interface used across frameworks. 

**I would like to propose the tool integration (including mcp) in `aichat` to simplify tool calls and agent definition.**

**Current Implementation/Workflow**

Right now, a user has to 
1. clone another framework (`llm-functions`) to even have the chance to integrate any type of functions/agents. 
2. go through the agent creation process as described (which is actually quite intuitive in general)
3. then link it to aichat. 

I have noticed that MPC is already supported there but still requires to go through the process of running a couple of commands.

I think it is a great idea to keep a collection of functions or agents in a seperate framework (I would even call it `aichat-tools` or `aichat-agents` to show that it is related to `aichat` even though it can be ran alone in theory), however, if someone runs a seperate MCP server which are available now in different programming langauge and versions, I propose an integration without any additional tools.

**Proposed Solution**

I am thinking of a solution where an agent is defined using a single `yaml` file. In the `aichat` config directory there is a folder where each file represents an agent, e.g. `agent/demo.yaml`. 

Each file in the folder is an agent a user can selected. The agent creation could be rather flexible to cover existing and future use-cases.

**1. Defining Functions Directly**

```
name: Personal Assistant
description: Your personal assistant for everyday tasks
version: 0.1.0
instructions: You are a Personal Assistant to answer all types of questions.
tools:
    function: hello_world
       command: demo.sh <args>
       description: A tool saying hello world
    function: square
       command: square.py <args>
```

**2. Defining A Function Collection (Fallback to current implementation)**

A fallback to the current solution where there is one `function.json` file that contains all functions that are available and a command parameter mapping it to the tool to be called.

```
...
tools:
    functions: functions.json
      command: bin/myagent <args>
```

It might be handy to offer include and exlude as options where include is a list of functions to be included (only this list and nothing else) and exclude functions to be prevented to be added.

e.g.

```
...
tools:
    functions: functions.json
      command: bin/myagent
      include: 
        - hello_world
```

This will become handy for larger collections and MCP servers described next.
Also, this would allow the `llm-functions` framework to be reduced to a collection of functions listed in a single `functions.json` file and functions to be imported as the user wishes.

**3. MCP Server**

Also, we allow the option to directly integrate an MCP server. By default we assume the server is already running or started by the user

```
...
tools:
    mcp: my_mcp_server
        endpoint: localhost
        port:8808
        include:
            - hello_world
```

but allow to add the run command to start it, if needed.

```
...
tools:
    mcp: my_mcp_server
        endpoint: localhost
        port:8808
        run: python fastmcpserver.py
```

The availability of functions could be determined whenever switching to an agent at run time by calling the `tools` endpoint.

**4. Mixed Tool Definition** 

And of course finally when creating an agent we could also combine all of it

```
...
tools:
     function: hello_world
       command: demo.sh
       description: A tool saying hello world
    functions: functions.json
      command: bin/myagent <args>
    mcp: my_mcp_server
        endpoint: localhost
        port:8808
        run: python fastmcpserver.py
```

The `function` collection could be nothing else than an agent called functions. I think this is how it is currently implemented in parts of the framework too.

**Summary**:

To summarize the pros of this solution:

1. An agent can be defined in a single `yaml` file with different options of how calls are executed.
2. Adding a function that calls a local binary file becomes straightforward.
3. The integration of tools/agents happens directly within `aichat`. No other libaries necessary. `llm-functions` co-exists as a collection of functions to be available to be imported either by using the `functions.json` as of right now or launching an MCP server.

I would love to discuss such a solution a little bit here in this thread/issue.
