### ISSUE TITLE
feature: add `--reason` cmdline arg similar to `--code`

### ISSUE THREAD

**Issue by peperunas** [sigoden/aichat#1223]
It would be great to have a way to remove and/or filter out the reasoning output from a model. Similar to what happens with code, basically.

**Comment by sigoden** [comment]
`--code` can also be used to strip the `<think>` tag.

**Comment by sigoden** [comment]
It works only if the `--code` flag is used and the terminal is not a tty.

```
aichat -m ollama:qwq --code 'Who are you?' | tee
```

**Comment by sigoden** [comment]
I always thought that the `<think>` tag would be automatically stripped if the --code flag is used and the terminal is not a TTY, but it turns out it isn't. I will fix it later.

**Comment by clh021** [comment]
> I always thought that the `<think>` tag would be automatically stripped if the --code flag is used and the terminal is not a TTY, but it turns out it isn't. I will fix it later.

Great!
Wow! Just wanted to chime in — I’m also hitting this exact issue after discovering aichat through llm-functions recently. Let me say this tool is pure wizardry 🔮! Hands down the most mind-blowing implementation I’ve seen in this space (seriously, the model call functions with shell  workflow is genius).

I’ve temporarily bypassed the problem by rotating between different models. Would love to contribute a PR eventually, though my Rust skills need some serious leveling up first ⚙️.

Huge props to the team — every time I use aichat it feels like watching a magic show where the rabbit actually improves the hat! 🎩✨ Keep up the stellar work!

**Comment by David-Else** [comment]
Sorry to jump in here, but I thought it was better than starting a new issue.

Qwen3 allows you to turn thinking on and off with `\think` and `\no_think` in the AIChat window. I am having problems configuring it and would like to ask for help.

1. Can i set a default role only for the Qwen3 model that starts with `\no_think` to turn it off?
2. Can i add it to my config file based on the example from the docs using curl?

https://qwen.readthedocs.io/en/latest/deployment/vllm.html#thinking-non-thinking-modes
```
curl http://localhost:8000/v1/chat/completions -H "Content-Type: application/json" -d '{
  "model": "Qwen/Qwen3-8B",
  "messages": [
    {"role": "user", "content": "Give me a short introduction to large language models."}
  ],
  "temperature": 0.7,
  "top_p": 0.8,
  "top_k": 20,
  "max_tokens": 8192,
  "presence_penalty": 1.5,
  "chat_template_kwargs": {"enable_thinking": false}
}'
```
I can't see how to add `"chat_template_kwargs": {"enable_thinking": false}` in my config?

```
    models:
      - name: meta-llama/Llama-3.3-70B-Instruct-Turbo-Free
        max_input_tokens: 131072
        input_price: 0
        output_price: 0
        supports_function_calling: true
      - name: Qwen/Qwen3-235B-A22B-fp8-tput
        max_input_tokens: 131072
        input_price: 0.2
        output_price: 0.6
```
Converting to YAML does not work:
```
      chat_template_kwargs:
        enable_thinking: false
```

Cheers!
