### ISSUE TITLE
Add option for macros to read session

### ISSUE THREAD

**Issue by jumski** [sigoden/aichat#1234]
**Is your feature request related to a problem? Please describe.**
I want to use macros to create and write summaries of my sessions, because I brainstorm a lot and would like an easy way to document what I figured out.
Currently it is impossible to let macros read the contents of a session because they are completely isolated.

Example macro I wanted to use:

```yaml
variables:
  - name: context
    rest: true
    default: ''
steps:
  - .model openai:o3-mini-high
  - .agent coder
  - |
    Create a summary doc from our discussion explaining the concept in such a way,
    that is clear to understand, concise, but covers all the major points.

    Mention only ideas we agreed on, or ideas that were considered good (if not agreed on, mention explicitly as alternatives).

    {{context}}

    Write a new file in docs/ folder. Name your file appropriately.
    Do not try to read any files from this folder or update/patch any existing docs.
    You can only create a new file.
``` 

I want to:
- always use a strong model for those summaries automatically
- activate agent so it can write files
- use a prompt with the ability to provide some additional context

**Describe the solution you'd like**
I want to allow macros to read the session contents without affecting the sessions when the macro finishes.
It would involve a new macro configuration option "read_session" which defaults to false.

```yaml
read_session: true
steps: ....
variables: .....
```

When set to true, the macro would be able to read the whole session contents.
Macro should not be able to affect the session, so when it finishes it is back to normal.

**Describe alternatives you've considered**
The only alternative really is to run those three commands manually and then revert to what was set previously (so, back to previous model and disable agent).

**Additional context**
none
