### ISSUE TITLE
how to use the openai flex pricing

### ISSUE THREAD

**Issue by garyblankenship** [sigoden/aichat#1270]
Would something like this work?

```
# ---- clients ----
clients:
  - type: openai
    api_base: https://api.openai.com/v1
    api_key: xxx
    models:
      - name: o4-mini
        max_input_tokens: 100000
        supports_function_calling: true
    patch:
      chat_completions:
        'o4-mini':
          body:
            service_tier: flex
```
