### ISSUE TITLE
claude 4 support

### ISSUE THREAD

**Issue by g19fanatic** [sigoden/aichat#1297]
Basically looking to get claude 4 support. Its out and the --sync-models models yaml isn't updated yet. I attempted to utilize it directly but getting "max_tokens" error as a req'd field. Does aichat need additional features to support it? idk.

**Comment by mcpiatkowski** [comment]
You can setup this in your config just like it is done in the `models.yaml`. Just do `.edit config` in REPL mode and add:

```yaml
clients:
  - type: claude
    api_key: your-api-key
    models:
      - name: claude-sonnet-4-20250514
        max_input_tokens: 200000
        max_output_tokens: 10000
        require_max_tokens: true  
```
