### ISSUE TITLE
Error with configuring Claude Sonnet

### ISSUE THREAD

**Issue by eldar** [sigoden/aichat#1314]
**Describe the bug**
Thanks for an awesome software project! I installed aichat and did a basic configuration with both Claude Sonnet 3.7 and 4. With both models I'm getting an error:
```
Error: Failed to call chat-completions api

Caused by:
    max_tokens: Field required (type: invalid_request_error)
```

**To Reproduce**
Here's the config I'm using (following the documentation).

```
model: claude:claude-3-7-sonnet-20250219:thinking
clients:
  - type: claude
    models:
      - name: claude-opus-4-20250514
        max_input_tokens: 200000
        max_output_tokens: 32000
        require_max_tokens: true
        input_price: 15
        output_price: 75
        supports_vision: true
        support_function_calling: true
      - name: claude-sonnet-4-20250514
        max_input_tokens: 200000
        max_output_tokens: 64000
        require_max_tokens: true
        input_price: 3
        output_price: 15
        supports_vision: true
        support_function_calling: true
      - name: claude-3-7-sonnet-20250219
        max_input_tokens: 200000
        max_output_tokens: 64000
        require_max_tokens: true
        input_price: 3
        output_price: 15
        supports_vision: true
        support_function_calling: true
```

**Expected behavior**
It should work right away.

**Configuration**
```
model                   claude:claude-3-7-sonnet-20250219:thinking
temperature             null
top_p                   null
use_tools               null
max_output_tokens       null
save_session            null
compress_threshold      4000
rag_reranker_model      null
rag_top_k               5
dry_run                 false
function_calling        true
stream                  true
save                    false
keybindings             emacs
wrap                    no
wrap_code               false
highlight               true
light_theme             false
config_file             /users/eldar/.config/aichat/config.yaml
env_file                /users/eldar/.config/aichat/.env
roles_dir               /users/eldar/.config/aichat/roles
sessions_dir            /users/eldar/.config/aichat/sessions
rags_dir                /users/eldar/.config/aichat/rags
macros_dir              /users/eldar/.config/aichat/macros
functions_dir           /users/eldar/.config/aichat/functions
messages_file           /users/eldar/.config/aichat/messages.md
```

**Environment (please complete the following information):**
- os version: Ubuntu 22.04/nixkpgs
- aichat version: 0.29.0
- terminal version: Kitty 0.42.1

**Comment by eldar** [comment]
Apologies for the noise, using actual configuration from models.yaml fixed the issue:

```yaml
      - name: claude-sonnet-4-20250514
        max_input_tokens: 200000
        max_output_tokens: 8192
        require_max_tokens: true
        input_price: 3
        output_price: 15
        supports_vision: true
        supports_function_calling: true
      - name: claude-sonnet-4-20250514:thinking
        real_name: claude-sonnet-4-20250514
        max_input_tokens: 200000
        max_output_tokens: 24000
        require_max_tokens: true
        input_price: 3
        output_price: 15
        supports_vision: true
        supports_function_calling: true
        patch:
          body:
            temperature: null
            top_p: null
            thinking:
              type: enabled
              budget_tokens: 16000
```
