### ISSUE TITLE
doc: Update Wiki with Model-Specific Patches and Model Aliases

### ISSUE THREAD

**Issue by milanglacier** [sigoden/aichat#1329]
I noticed the AiChat wiki appears to be missing documentation for some key features, specifically model aliases, model-specific patches, and creating different configurations for the same provider.

I've drafted concise explanations of these features based on my understanding. Please feel free to incorporate them into the wiki as needed, especially if you're short on time to write the documentation yourself.

Thank you for creating such a fantastic application!

**Suggested Wiki Update**:

## Patching API Requests

**Model-Specific Patches**

Instead of applying patches to the entire provider configuration, you can target specific models. For instance:

**Controlling the Thinking Budget for Gemini:**

```yaml
# This creates a model alias, gemini-2.5-pro-minimal-thinking, for gemini-2.5-pro.
  - type: gemini
    models:
      - name: gemini-2.5-pro-minimal-thinking
        real_name: gemini-2.5-pro
        patch:
          body:
            generationConfig:
              thinkingConfig:
                thinkingBudget: 128
```

**Enabling Search for Gemini:**

```yaml
  - type: gemini
    models:
      - name: gemini-2.5-flash-search
        real_name: gemini-2.5-flash
        patch:
          body:
            tools:
              - google_search: {}

```

Additionally, I recommend adding the following section below "Add client for openai-compatible API provider":

## Creating Different Configurations for the Same Provider

You can create multiple different configurations for a single provider. For example, the following configuration creates a Gemini provider named `G`, distinct from the standard Gemini provider with its own unique configuration:

```yaml
clients:
  - type: gemini
    name: G
    models:
      - name: gemini-2.5-pro-no-thinking
        real_name: gemini-2.5-pro
        patch:
          body:
            generationConfig:
              thinkingConfig:
                thinkingBudget: 128
```

**Suggested Wiki updates end here**

Please also note that I created the `G` alias for Gemini primarily because I rely on the `aichat --sync-models` feature to fetch the latest model information, such as context window sizes.

I noticed that if I don’t create a custom alias that patches the existing `gemini` provider, it completely overrides the model data from `model_overrides.yaml`. This prevents me from accessing the synchronized model information.

To resolve this, I have to create a separate `G` alias for my custom Gemini models (e.g., those with search enabled or "thinking" disabled). This approach allows me to use both the officially synchronized models from `model_overrides.yaml` and my own patched configurations simultaneously.

I would appreciate any suggestions for a more elegant solution (if you have any) to this scenario. Thanks!
