### ISSUE TITLE
`.clear role` and `.clear history` does not work with `session`

### ISSUE THREAD

**Issue by milanglacier** [sigoden/aichat#165]
below is a session named: `hello.yaml`, where I defined a role `polish`:

```yaml
path: null
model: openai:gpt-3.5-turbo-16k
tokens: 303
messages:
- role: system
  content: |
    I am seeking your expertise as a language expert to refine and polish the text I provide. Please focus on improving the wording without adding any additional comments, and send the improved text directly back to me.
- role: user
  content: The TV business is in flux once again. As a result, the risky, rule-breaking shows that defined television in the early 21st century are giving way to less original fare.
- role: assistant
  content: The television industry is undergoing another period of transformation. Consequently, the daring and boundary-pushing programs which characterized television in the early 21st century are being replaced by less innovative content.
- role: user
  content: The TV business is in flux once again. As a result, the risky, rule-breaking shows that defined television in the early 21st century are giving way to less original fare.
- role: assistant
  content: The television industry is once again experiencing a period of transition. Consequently, the daring and rule-breaking shows that defined television in the early 21st century are now being overshadowed by less pioneering content.
- role: user
  content: The TV business is in flux once again. As a result, the risky, rule-breaking shows that defined television in the early 21st century are giving way to less original fare.
- role: assistant
  content: The television industry is undergoing another period of change. As a result, the adventurous and groundbreaking shows that defined television in the early 21st century are now being replaced by less innovative content.
```

## `.clear history` not work:

step to reproduce:

```
aichat -s hello

.clear history
<Ctrl-D>
```

**Expected behavior**: the content of `hello.yaml` should be cleared.
**Actual behavior**: the content of `hello.yaml` unchanged.

## `.clear role` not work:

step to reproduce:

```
aichat -s hello

.clear role

```

**Expected behavior**: the role has been cleared (and if needed, we can clear history before clearing role), and we can reassign a role
**Actual behavior**: get the following error: `Cannot perform this action in session`
