### ISSUE TITLE
How to access gpt-4-1106-preview

### ISSUE THREAD

**Issue by johnnywiller** [sigoden/aichat#223]
New OpenAI model `gpt-4-1106-preview`

**Comment by madnight** [comment]
You can specify:
```
model: openai:gpt-4-1106-preview
clients:
  - type: openai
    api_key: YOURKEY
    connect_timeout: 10
```
works for me.

**Comment by johnnywiller** [comment]
really? for me I get

```
 ~/Desktop/ aichat --version
aichat 0.9.0
 ~/Desktop/ aichat --info
Error: Unknown model 'openai:gpt-4-1106-preview'
```

**Comment by johnnywiller** [comment]
Please try `aichat --model gpt-4-1106-preview` let me know if it works

**Comment by sigoden** [comment]
For users who want to immediately experience access to GPT-4-1106-preview in aichat v0.9.0, you can follow these steps.

1. add the following snippet to the `config.yaml` file
```
clients:
  - type: openai
    api_key: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  - type: localai
    name: openai2
    api_base: https://api.openai.com/v1
    api_key: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    models:
      - name: gpt-4-1106-preview
        max_tokens: 128000
```

2. use the model

```
aichat --model openai2:gpt-4-1106-preview

.model openai2:gpt-4-1106-preview
```
