### ISSUE TITLE
Mistral Platform Support

### ISSUE THREAD

**Issue by skiman6010** [sigoden/aichat#269]
### Please confirm whether the following requirements are met:

- [x] Must have a REST/HTTP API.
- [x] Must be publicly accessible. It cannot require application review or have regional restrictions. A beta version is acceptable.
- [x] No open source. Open source models can be used through LocalAI and do not need to be supported separately.
- [x] Cannot be an agent/proxy of other platforms.

### Please provide the following documents or links:

- API Documentation (required)
https://docs.mistral.ai/api
- TOKEN calculation document (optional)
https://docs.mistral.ai/platform/pricing

Mistral is offering their models hosted on their platform. It is currently behind a waitlist, but access is rapidly expanding. I would love to see aichat support.

**Comment by thsunkid** [comment]
Desperately need this. Could I send a PR?

**Comment by sigoden** [comment]
As the api of the mistral ai is compatiable with openai/localai API, you can use mistralai with localai client.

```
clients:
  - type: localai
    name: mistral
    api_base: http://api.mistral.ai/v1
    models:
      - name: mistral-tiny
        max_tokens: 8192
```
