### ISSUE TITLE
ollama documentation is unclear

### ISSUE THREAD

**Issue by Nepherim** [sigoden/aichat#284]
Is there support for local ollama models? It seems so from the home page, but it's unclear what config to use. This [does not work for example](https://github.com/sigoden/aichat/pull/276):
```
clients:
  - type: ollama
    api_base: http://localhost:11434/api
    models:
      - name: codellama
      - name: llava
  ```
