### ISSUE TITLE
Allow providing assistant messages in roles (one-shot / few-short) "learning"

### ISSUE THREAD

**Issue by JojiiOfficial** [sigoden/aichat#295]
**Is your feature request related to a problem? Please describe.**
Sometimes a system prompt is not enough and some few examples (one-shot / few-show) can help a lot to get desirable output.

**Describe the solution you'd like**
I want to be able to provide some assistant and user messages in a role that give the model additional information how to respond.

The yaml format could be something like

```yaml
- name: myprompt
  prompt: ...
  examples:
    - user: "SomeInput"
      assistant: "CorrectedInput"
    - assistant: ".."
```

Where the 'user' key is optional and the examples get also sent to the model before the repl-read user message.
I can contribute something like that but I'd like to discuss it before.
