### ISSUE TITLE
Gemeni-pro

### ISSUE THREAD

**Issue by fvkd** [sigoden/aichat#307]
I saw in the README that aichat supports Gemini-Pro models. I'm running aichat 0.12.0. Only seeing Open-AI models when I auto-complete or manually try to enter any models on the cli. Just wondering if its on a feature to-do list or in the 0.12.0 release? Thanks so much for your awesome work.

**Comment by sigoden** [comment]
AIChat v0.12.0 already supports Gemini. To use it, you need to configure a Gemini client first.

Make sure you've added the following configuration items in your `config.yaml`:

```yaml
clients:
  - type: gemini
    api_key: AIxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
