### ISSUE TITLE
Context Window vs Output Tokens on gpt-4-turbo-preview

### ISSUE THREAD

**Issue by workflow** [sigoden/aichat#338]
Hi and thank you for this fantastic interface! 😻 🦀

The new preview OpenAPI models like `gpt-4-turbo-preview` seem to have a large context window (128,000 tokens) but a rather small output token limit (4096 tokens)

![image](https://github.com/sigoden/aichat/assets/1276854/96fa7413-c2bf-4eb4-9936-f9d32abc38cf)

I may be misunderstanding how  this works, but it seems to me that `aichat` is not allowing these newer models the full context window, and instead limiting what we send to the *output token* limit.

For example in my config I have:

```yaml
clients:
  - type: openai
    models:
      - name: gpt-4
        max_tokens: 8192
      - name: gpt-4-turbo-preview
        max_tokens: 128000
```

...but starting a session with `aichat --model openai:gpt-4-turbo-preview --session new` gives me a session with 4,096 max tokens, and errors out once that limit is reached.

Is this is a bug or am I just misunderstanding how it works?
