### ISSUE TITLE
Failed to get answer. Caused by: Invalid header value

### ISSUE THREAD

**Issue by ZzzzRyan** [sigoden/aichat#349]
**Describe the bug**
when I send message in REPL mode, It appears the following error:

```ps
Failed to get answer

Caused by:
    Invalid header value: "text/html; charset=utf-8"
```

**To Reproduce**

```ps
$ aichat
# -> Welcome to aichat 0.14.0
# -> Type ".help" for more information.
> hello
Failed to get answer

Caused by:
    Invalid header value: "text/html; charset=utf-8"

> 
```

**Expected behavior**
Normal answer

**Screenshots/Logs**
![image](https://github.com/sigoden/aichat/assets/107601663/dae50123-a1a7-42b6-8a77-99019ad163b0)

**Environment (please complete the following information):**
- os version: Windows 10 22H2
- aichat version: 0.14.0
- terminal version: PowerShell, Windows Terminal 1.20.10572.0

**Additional context**
config:
```yaml
model: openai:gpt-4              # LLM model
temperature: 0.7                 # GPT temperature, between 0 and 2
save: true                       # Whether to save the message
highlight: true                  # Set false to turn highlight
light_theme: false               # Whether to use a light theme
wrap: no                         # Specify the text-wrapping mode (no, auto, <max-width>)
wrap_code: false                 # Whether wrap code block
auto_copy: false                 # Automatically copy the last output to the clipboard
keybindings: vi                  # REPL keybindings. (emacs, vi)
prelude: ''                      # Set a default role or session (role:<name>, session:<name>)

clients:
- type: openai
  api_key: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  api_base: https://xxxxxxx (my service)
```
