### ISSUE TITLE
what is the default model? setup a default model

### ISSUE THREAD

**Issue by engie-b2c-perf** [sigoden/aichat#361]
**Is your feature request related to a problem? Please describe.**
it is not really a problem, but I am confused about which model will be used by default in case I have various models set up.

That's my `config.yaml` : 

```yaml
clients:
  - type: vertexai
    api_base: https://{REGION}-aiplatform.googleapis.com/v1/projects/{PROJECT_ID}/locations/{REGION}/publishers/google/models
  - type: ollama
    api_base: http://localhost:11434
    models:
    - name: llama2
      max_input_tokens: null
```

Modles are recognized:

```sh
$ aichat --list-models
vertexai:gemini-1.0-pro
vertexai:gemini.1.0-pro-vision
vertexai:gemini-1.0-ultra
vertexai:gemini.1.0-ultra-vision
vertexai:gemini-1.5-pro
ollama:llama2
$ aichat
>
# what is the active default model here? 
```

**Describe the solution you'd like**
I would like:
* to know what the current model is in chat mode _=> important to me_
* to define a default model in `config.yaml`. For that I guess we can use the field `prelude: model:<name> _=> important to me_
* bonus: to restrict models that can be used for one client. For example, here I could restrict vertexai to only one model:
  ```sh
  $ aichat --list-models
  vertexai:gemini-1.0-pro
  ollama:llama2
  ```

**Describe alternatives you've considered**
I tried playing with `config.yaml` to do that but it didn't work

Tried to force one model like this:

```yaml
clients:
  - type: vertexai
    api_base: https://{REGION}-aiplatform.googleapis.com/v1/projects/{PROJECT_ID}/locations/{REGION}/publishers/google/models
    models:
    - name: vertexai:gemini-1.0-pro
  - type: ollama
    api_base: http://localhost:11434
    models:
    - name: llama2
      max_input_tokens: null
```

Thanks for the help!
Your tool is great
