### ISSUE TITLE
Use free ChatGPT 3.5

### ISSUE THREAD

**Issue by xsigoking** [sigoden/aichat#390]
Since openai provides a login-free chatgpt website, we can get unlimited free GPT-3.5 API.

### 1. run the chatgpt-free-api server

create a `docker-compose.yaml` file
```yaml
version: '3'

services:
  chatgpt-free-api:
    image: xsigoking/chatgpt-free-api:latest
    restart: always
    ports:
      - "3040:3040"
```

start the server
```
docker-compose up -d
```

See https://github.com/xsigoking/chatgpt-free-api for more details.

### 2. configure the client

edit `<aichat-config-dir>/config.yaml` to add a new client

```yaml
clients:
  - type: openai-compatible
    name: chatgpt
    api_base: http://127.0.0.1:3040/v1
    models:
      - name: gpt-3.5
        max_input_tokens: 16385
```

### 3. use the free chatgpt-3.5 api

![showcase](https://github.com/sigoden/aichat/assets/152482559/c9274f38-7734-45fb-9ac3-86e77a3cbea9)

## Further thoughts

Is it possible for aichat to add a new type of client  to avoid running third party service?

```yaml
clients:
- type: chatgpt
```
