### ISSUE TITLE
Config - store API keys separately

### ISSUE THREAD

**Issue by inifares23lab** [sigoden/aichat#421]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/sigoden/aichat/issues) before creating one.

If you are requesting support for the new model, goto [model-request](https://github.com/sigoden/aichat/issues/new?assignees=&labels=enhancement&projects=&template=model_request.md&title=).

**Is your feature request related to a problem? Please describe.**
I keep the config file in version control with multiple models
I also use models with an API key, I'd like to store my config but avoid keeping the keys in version control and still keeping things simple (i.e. just use yaml config, no secret stores, no DBs...)

**Describe the solution you'd like**

store API keys separately somehow..maybe like this:

config.yaml
```
...
- type: ollama
  api_base: http://127.0.0.1:11434
  api_key: null
  models:
  - name: orca-mini:latest
    max_input_tokens: null

- type: gemini
  api_key: !include api_keys.yaml gemini_api_key/

- type: openai
  api_key: !include api_keys.yaml openai_api_key/
...
```

api_keys.yaml
```
gemini_api_key: "api key"
openai_api_key: "api key"
```
