### ISSUE TITLE
Add Groq

### ISSUE THREAD

**Issue by jacksongoode** [sigoden/aichat#422]
### Please confirm whether the following requirements are met:

- [ x] Must have a REST/HTTP API.
- [ x] Must be publicly accessible. It cannot require application review or have regional restrictions. A beta version is acceptable.
- [ x] Must not act as an agent or proxy for other platforms.

> Tip: If the API of the new model is compatible with OpenAI's API, it can be used through localai client.

### Please provide the following documents or links:

- API Documentation (required)
https://wow.groq.com/

- TOKEN calculation document (optional)
https://wow.groq.com/

**Comment by sigoden** [comment]
Since groq api is comptabile with openai api, we can use `openai-compatiable` client.

```
  - type: openai-compatible
    name: groq
    api_base: https://api.groq.com/openai/v1
    api_key: xxxxxxxxxx
    models:
      - name: llama3-70b-8192
        max_input_tokens: 8192
```
