### ISSUE TITLE
add llamafile - is the API really compatible ?

### ISSUE THREAD

**Issue by colindaven** [sigoden/aichat#446]
Thanks for the great looking tool. I am particularly keen on local LLMs and have experienced problems downloading ollama models on systems behind a proxy.

Llamafile must be about the easiest LLM to run, since you only need to wget and chmod a+x. The API docs look a little scarce, but maybe it would be a relevant one to add in future.

https://github.com/Mozilla-Ocho/llamafile/

Thanks

### Please confirm whether the following requirements are met:

- [ ] Must have a REST/HTTP API.
- [x] Must be publicly accessible. It cannot require application review or have regional restrictions. A beta version is acceptable.
- [x] Must not act as an agent or proxy for other platforms.

> Tip: If the API is compatible with OpenAI's API, you can access it using the `openai-compatible` client.

### Please provide the following documents or links:

- https://github.com/Mozilla-Ocho/llamafile/blob/main/llama.cpp/server/README.md#api-endpoints

**Comment by sigoden** [comment]
![image](https://github.com/sigoden/aichat/assets/4012553/1db5868f-5af2-49b5-9072-7767564ce799)

It may have supported an OpenAI-compatible API.

you can try the following configuration
```
clients:
  - type: openai-compatible
    name: llamafile
    api_base: http://localhost:8080/v1
    models:
      - name: default
        max_input_tokens: 16385
        max_output_tokens: 2048
```
