### ISSUE TITLE
confused with openai-compatible

### ISSUE THREAD

**Issue by sparkssssssssss** [sigoden/aichat#482]
I am confused about custom API configuration,
because Gemini has changed its strategy. I want to use my own OneAPI to support Aichat according to the instructions, but it is not working . Please advise.

````
model: openai:gpt-4
light_theme: true
highlight: false
clients:
- type: openai-compatible
  name: localai
  api_base: https://mydomain/v1
  api_key: sk-xxxxxx
  chat_endpoint: /chat/completions  
  models:
    - name: gpt-4
      max_input_tokens: 8192
````

test result below:
````
Failed to get answer

Caused by:
    0: error decoding response body
    1: expected value at line 1 column 1
````
