### ISSUE TITLE
Invalid Ollama prompt structure yields empty responses

### ISSUE THREAD

**Issue by tzok** [sigoden/aichat#498]
**Describe the bug**
According to the [docs](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-completion) the request should contain:
```json
{
  "model": "...",
  "prompt": "Why is the sky blue?"
}
```

However, `aichat` sends:
```json
{
  "model": "...",
  "messages": [
    {
      "role": "user",
      "content": "Why is the sky blue?"
    }
  ]
}
```

Because of the missing `prompt`, I receive empty responses.

**To Reproduce**
Configure the Ollama client in `~/.config/aichat/config.yaml`:
```yaml
...
clients:
  - type: ollama
    api_base: ...
    api_auth: ...
    chat_endpoint: ...
    models:
      - name: llama2
```

Try to run it:
```
aichat -m ollama:llama2 Why is the sky blue?
```

**Expected behavior**
I expect to receive a response, but Ollama sends an empty one.

**Environment (please complete the following information):**
- os version: Arch Linux
- aichat version: 0.16.0
- terminal version: Alacritty 0.13.2

**Additional context**
I have printed the complete request that `aichat` produces (in `src/client/ollama.rs:49`):
```
$URL {"model":"llama2","messages":[{"role":"user","content":"Why is the sky blue?"}],"stream":true,"options":{"temperature":1.0}}
```
