### ISSUE TITLE
Error: No available model in 0.17.0 (MacOS/Brew)

### ISSUE THREAD

**Issue by hxii** [sigoden/aichat#533]
**Describe the bug**
- After moving to (and upgrading from 0.12.0) aichat through brew, I get the "No available model" error.
- I tried removing the config and reinstalling aichat through brew.
- I recreated the `config.yaml` file from the example, as removing it and running aichat wouldn't give me the prompt to create the config anew.

**Configuration**
```YAML
model: openai:gpt-4o # Specify the language model to use
temperature: null # Set default temperature parameter
top_p: null # Set default top-p parameter
save: true # Indicates whether to persist the message
save_session: null # Controls the persistence of the session, if null, asking the user
highlight: true # Controls syntax highlighting
light_theme: false # Activates a light color theme when true. ENV: AICHAT_LIGHT_THEME
wrap: no # Controls text wrapping (no, auto, <max-width>)
wrap_code: false # Enables or disables wrapping of code blocks
auto_copy: false # Enables or disables automatic copying the last LLM response to the clipboard
keybindings: emacs # Choose keybinding style (emacs, vi)
prelude: null # Set a default role or session to start with (role:<name>, session:<name>)

# Command that will be used to edit the current line buffer with ctrl+o
# if unset fallback to $EDITOR and $VISUAL
buffer_editor: null

# Controls the function calling feature. For setup instructions, visit https://github.com/sigoden/llm-functions.
function_calling: false

# Compress session when token count reaches or exceeds this threshold (must be at least 1000)
compress_threshold: 1000
# Text prompt used for creating a concise summary of session message
summarize_prompt: "Summarize the discussion briefly in 200 words or less to use as a prompt for future context."
# Text prompt used for including the summary of the entire session
summary_prompt: "This is a summary of the chat history as a recap: "

# Custom REPL prompt, see https://github.com/sigoden/aichat/wiki/Custom-REPL-Prompt
left_prompt: "{color.green}{?session {session}{?role /}}{role}{color.cyan}{?session )}{!session >}{color.reset} "
right_prompt: "{color.purple}{?session {?consume_tokens {consume_tokens}({consume_percent}%)}{!consume_tokens {consume_tokens}}}{color.reset}"

clients:
  # All clients have the following configuration:
  # - type: xxxx
  #   name: xxxx                                      # Only use it to distinguish clients with the same client type. Optional
  #   models:
  #     - name: xxxx                                  # The model name
  #       max_input_tokens: 100000
  #       supports_vision: true
  #       extra_fields:                               # Set custom parameters, will merge with the body json
  #          key: value
  #   extra:
  #     proxy: socks5://127.0.0.1:1080                # Set https/socks5 proxy. ENV: HTTPS_PROXY/https_proxy/ALL_PROXY/all_proxy
  #     connect_timeout: 10                           # Set timeout in seconds for connect to api

  # See https://platform.openai.com/docs/quickstart
  - type: openai
    api_key: <REDACTED> # ENV: {client}_API_KEY
    api_base: https://api.openai.com/v1 # ENV: {client}_API_BASE
    models:
      - name: gpt-4o
        max_input_tokens: 128000
        max_output_tokens: 4096
        input_price: 5
        output_price: 15
        supports_vision: true
        supports_function_calling: true

  # For any platform compatible with OpenAI's API
```

**Environment:**
- os version: MacOS Sonoma 14.4
- aichat version: 0.17.0
- terminal version: wezterm 20240203-110809-5046fc22

**Comment by denniswebb** [comment]
I believe I got this earlier and the solution was to create an empty roles.yaml with `touch ~/Library/Application\ Support/aichat/roles.yaml`

**Comment by sigoden** [comment]
Due to a lack of feedback, this issue is being closed.

**Comment by hxii** [comment]
Apologies for not replying sooner, didn't have the time.
@sigoden `aichat --info` fails on the same error, even when I tried what @denniswebb suggested:
```
~/dev ❱ ll  ~/Library/Application\ Support/aichat/roles.yaml
Permissions Size User         Date Modified Name
.rw-r--r--@ 1.2k Paul_Glushak 27 May 11:15  '/Users/Paul_Glushak/Library/Application Support/aichat'/roles.yaml
~/dev ❱ aichat --info
Error: No available model
```

**Comment by sigoden** [comment]
see https://github.com/sigoden/aichat/issues/540#issuecomment-2130321262

**Comment by hxii** [comment]
@sigoden Unless I'm missing something, my config file has the required info
```
clients:
  - type: openai
    api_key: <REDACTED>
    api_base: https://api.openai.com/v1 # ENV: {client}_API_BASE
    models:
      - name: gpt-4o
        max_input_tokens: 128000
        max_output_tokens: 4096
        input_price: 5
        output_price: 15
        supports_vision: true
        supports_function_calling: true
```
