### ISSUE TITLE
Ollama streaming can break when going through a reverse proxy

### ISSUE THREAD

**Issue by ProjectMoon** [sigoden/aichat#548]
**Describe the bug**
If ollama is run through a reverse proxy, e.g. nginx, the code that handles the streaming response can sometimes fail to parse the JSON response due to the entirety of the JSON line not being available yet. Sometimes it works, sometimes it doesn't. This is with `proxy_buffering off` and other relevant options in the nginx config.

**To Reproduce**
Set up ollama. Proxy through nginx with a config like this:

```
    location /api/ {
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_set_header Origin '';
        proxy_set_header Referer '';
        proxy_pass http://localhost:11434/api/;
    }
```

**Expected behavior**
Streaming works properly.

**Screenshots/Logs**
Instead, you will often get an error like this:

```
Failed to get answer

Caused by:
    trailing characters at line 2 column 1
```

**Configuration**
Running from latest `main`.

model               agnosis:llama3:instruct
max_output_tokens   -
temperature         1
top_p               -
function_calling    false
compress_threshold  8192
dry_run             false
save                false
save_session        -
highlight           true
light_theme         true
wrap                auto
wrap_code           false
auto_copy           false
keybindings         emacs
prelude             -
config_file         /home/user/.config/aichat/config.yaml
roles_file          /home/user/.config/aichat/roles.yaml
messages_file       /home/user/.config/aichat/messages.md
sessions_dir        /home/user/.config/aichat/sessions
functions_dir       /home/user/.config/aichat/functions

**Environment (please complete the following information):**
- os version: Gentoo
- aichat version: `4fa92b020aaf0f473a4953b21e14818d6e779208`
- terminal version: GNOME Terminal 3.50.1

**Additional context**
I have made a PR that updates the ollama client to use the JSON streaming you've already built, and it appears to work perfectly. I will open it momentarily.

**Comment by oatmealm** [comment]
Sorry it it's not related, but I'm seeing this right now with aichat 0.21.1.

```
aichat -e hello
Failed to call chat-completions api

Caused by:
    0: error decoding response body
    1: trailing characters at line 1 column 5
```

```
clients:
  - type: openai-compatible
    name: ollama
    api_base: http://[remote]:11434         
    models:                                      
      - name: llama3.1-8b-instruct-q6_K
        max_input_tokens: 8192
        supports_function_calling: true
      - name: bge-m3
        type: embedding
        max_tokens_per_chunk: 8192
        default_chunk_size: 1024
        max_batch_size: 20
```

```
model: ollama:llama3.1-8b-instruct-q6_K      # Specify the language model to use
temperature: 0.2                # Set default temperature parameter
```
