### ISSUE TITLE
Function calling does not seem to work with ollama models

### ISSUE THREAD

**Issue by tomsib2001** [sigoden/aichat#569]
I'm not sure if this is because the models are not smart enough to understand how to call a function, or if something inherently prevents them from calling functions, but here is what I am getting:

```shell
 aichat -r %functions% --model azure_ai:gpt-4-turbo-1106-preview what is the weather i
n paris ?
Call get_current_weather '{"location":"Paris"}'
The current weather in Paris is partly cloudy with a temperature of +21°C and a moderate northeast wind blowing at 5.3 meters per second.
```

but
```shell
 aichat -r %functions% --model ollama:llama3:8b what is the weather in paris ?
Paris, the City of Light! The weather in Paris can be quite unpredictable, but I'll give you an update on what's currently happening.
[etc...]
```

I tried repeatedly, with various models, including `llama3:70b` which is supposed to be quite a bit smarter.

my config file looks like
```yaml
save: true
conversation_first: true # optional, If set true, start a conversation immediately upon repl
function_calling: true
compress_threshold: 50000
[...]
- type: azure-openai
  name: azure_ai
  api_base: http://[HOSTNAME]:8080/api/azure/
  api_key: [API_KEY]
  models:
    - name:  gpt-4-turbo-1106-preview # 128k
      max_input_tokens: 128000
      max_output_tokens: 4096
      supports_function_calling: true
- type: ollama
  api_base: http://[HOSTNAME]
  models:
    - name: llama3:8b
      supports_function_calling: true
```
