### ISSUE TITLE
Error: Invalid prelude '

### ISSUE THREAD

**Issue by tkanarsky** [sigoden/aichat#619]
**Describe the bug**
After upgrading from 0.17 -> head of main and installing via `cargo install --path .`, results in `Error: Invalid prelude '` being returned. Error code is 1.

**To Reproduce**
- `git fetch && git checkout 2eab71a641827e503b14952373aec82661192ba2`
- `cargo install --path .`
- `aichat`

**Expected behavior**
Thing works as before (opening repl)

**Screenshots/Logs**

**Configuration**
```
model               openai:gpt-4o
max_output_tokens   -
temperature         1
top_p               -
rag_top_k           4
function_calling    true
compress_threshold  10000
dry_run             false
save                true
save_session        -
highlight           true
light_theme         false
wrap                no
wrap_code           false
keybindings         vi
prelude             
config_file         /home/tkanarsky/.config/aichat/config.yaml
roles_file          /home/tkanarsky/.config/aichat/roles.yaml
functions_dir       /home/tkanarsky/.config/aichat/functions
rags_dir            /home/tkanarsky/.config/aichat/rags
bots_dir            /home/tkanarsky/.config/aichat/bots
sessions_dir        /home/tkanarsky/.config/aichat/sessions
messages_file       /home/tkanarsky/.config/aichat/messages.md
```

**Environment (please complete the following information):**
- os version: Ubuntu 20.04
- aichat version: 0.18 prerelease? idk, whatever git commit 2eab71a641827e503b14952373aec82661192ba2 is
- terminal version: guake 3.6.3

**Additional context**
I bet this is a config file error, here's my config:

```
model: openai:gpt-4o      # LLM model
function_calling: true
temperature: 1.0                 # GPT temperature, between 0 and 2
save: true                       # Whether to save the message
highlight: true                  # Set false to turn highlight
light_theme: false               # Whether to use a light theme
wrap: no                         # Specify the text-wrapping mode (no, auto, <max-width>)
wrap_code: false                 # Whether wrap code block
auto_copy: false                 # Automatically copy the last output to the clipboard
keybindings: vi               # REPL keybindings. (emacs, vi)
prelude: ''                      # Set a default role or session (role:<name>, session:<name>)

# Compress session if tokens exceed this value (valid when >=1000)
compress_threshold: 10000
# The prompt for summarizing session messages
summarize_prompt: 'Summarize the discussion briefly in 500 words or less to use as a prompt for future context.'
# The prompt for the summary of the session
summary_prompt: 'This is a summary of the chat history as a recap: '

# Custom REPL prompt, see https://github.com/sigoden/aichat/wiki/Custom-REPL-Prompt
left_prompt: '{color.green}{?session {session}{?role /}}{role}{color.cyan}{?session )}{!session >}{color.reset} '
right_prompt: '{color.purple}{?session {?consume_tokens {consume_tokens}({consume_percent}%)}{!consume_tokens {consume_tokens}}}{?running_cost , ~{running_cost} so far}{?context_cost , ~{context_cost} per message} {color.reset}'

clients:
  # See https://platform.openai.com/docs/quickstart
  - type: openai
    api_key: <redacted>
    api_base: https://api.openai.com/v1               # Optional field

  # See https://ai.google.dev/docs
  - type: gemini
    api_key: <redacted>

  # See https://docs.anthropic.com/claude/reference/getting-started-with-the-api
  - type: claude
    api_key: <redacted>

  # - type: mistral
  #   api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

  - type: openai-compatible
    api_base: <redacted> 
    chat_endpoint: /chat/completions                  # Optional field
    models:
      - name: llama3-70b
        capabilities: text
        extra_fields:
            max_tokens: 4096                                # Optional field, set custom parameters
            stop: ["<|start_header_id|>", "<|end_header_id|>", "<|eot_id|>", "<|reserved_special_token|>"]
```
