### ISSUE TITLE
RAG enhancement. Add chroma, qdrant, etc vector databases collection context to queries

### ISSUE THREAD

**Issue by ctappy** [sigoden/aichat#673]
**Describe the solution you'd like**
I am a little new to AI so I am not sure about this direction or even if this is already implemented and I missed it, I can potentially help with the development too

I didn't see qdrant, chromadb etc options to add into the rag system. if I/someone added in these would the following config options and aichat options work?

#### config
```
vector_database:
  - name: my_db
    database_type: chromadb
    connection: localhost:8000
    default_collection: all_collection
```
#### cli
```
aichat --vector-database my_db --vector-database-collection other_collection
```
