### ISSUE TITLE
Web Search

### ISSUE THREAD

**Issue by sigoden** [sigoden/aichat#679]
## Problem 1

Many agents require web search capability. 

The implementation of web_search should be flexible.  For example, users who prefer DuckDuckGo should be able to use `search_duckduckgo` as their web search tool, while users who favor Tavily could opt for `search_tavily`.

Currently, AIChat doesn't offer this capability, let alone flexibility.

## Problem 2

Currently, tools are tied to specific roles (via the `functions_filter` field), and these roles are mutually exclusive.

We could create a dedicated web search role:

```yaml
- name: web_search
  functions_filter: search_tavily
```

However, this web search role couldn't be combined with other roles or used within existing sessions.

## Solution

Add the following configuration to the `config.yaml` file:

```yaml
mapping_tools:
  web_search: 'search_tavily'
  code_interpreter: 'execute_py_code'
```

> Currently, only these three mappers are supported. This restriction may be relaxed in the future, allowing users to add any mapper they need.

The agent definition file (`index.yaml`) supports the following configuration:

```yaml
common_tools:
  - web_search
  - code_interpreter
```

> The possible values for agent's common_tools are: web_search and code_interpreter. There are no others.

Then, make the `role`/`session` supports a new configuration item: `use_tools`.

```yaml
use_tools: web_search
use_tools: web_search,code_interpreter
use_tools: web_search,save_file
use_tools: all
```

You can change the value of `use_tools` at any time using `.set`.

```
.set use_tools web_search
.set use_tools web_search,save_file
.set use_tools all
```

## Additional Context

Some LLMs natively support web search, such as `cohere:command-r*` `ernie:*` `perplexity:*-online`.

Should there be a way to use this feature?

## Final

Welcome all solutions or suggestions.
