### ISSUE TITLE
Dynamic prompts / context using function calling

### ISSUE THREAD

**Issue by einarpersson** [sigoden/aichat#689]
**Is your feature request related to a problem? Please describe.**
Some roles and agents need context that are dynamic. This could be current time, current working directory, clipboard content, current ssid name, etc etc. The natural way to facilitate this is to use function calling. However, it may create unnecessary roundtrips costing tokens and creating latency. I may also cause unneccessary ambiguity (should I call this function or not?), whereas the user may want to force the role/agent to always have up to date information regarding X Y and Z (and preferably without having to instruct that in the prompt). It may not even be relevant to use the function call again during a session, it could just be a way to provide an accurate context.

**Describe the solution you'd like**
I propose that we let role prompts (as defined in `roles.yaml`) and agent instructions (`agentfoo/index.yaml`) include some kind of function calling syntax, that can reuse the available tools for that role/agent.  Perhaps using `{ }` or `{{ }}`. I understand that it may become verbose if there are many complex calls, but that is only if the user choose to do so. It will not make the default case different. I think this would make it possible to write very powerful roles and agents that always have the necessary context predefined to increase the success rate.

```yaml
- name: myrole
  prompt: "You are helping the user with X. Here is some context\n
Time: {get_time()}\n
Location: {get_location()}\n
Something else: {fetch_from_api('blablabllba')}\n
\n
Please Y."
```

```yaml
name: Todo
description: A helpful ai agent that manages a todo list.
instructions: '
  You will be provided with a list of todos.
  The current list is {list_todos()}
  Users can interact with you using the following commands:
    * add_todo: Add a todo to the list.
    * rm_todo: Remove a todo from the list. 
    * list_todos: Display the current todo list. 
#  ...
```

**Describe alternatives you've considered**
1. Alt: I saw that there is some support for injecting context. Perhaps it could be provided in that framework if that makes more sense. 

2. Alt: Restrict this kind of advanced feature to agents. Have a special function eg. `make_context()` that the user can choose to implement or not. Make sure this is called and injected at point of `___CONTEXT___` in agent instruction.

What do you think? :) I would really like to unleash the possibility to inject dynamical content using tools in the first prompt, without having the LLM having to figure that part out.

**Comment by sigoden** [comment]
Thank you for your feedback, but we will reject this propsal.

## Drawback

**1. Your intention was to reduce token usage, but your current strategy could actually lead to using even more tokens.**

For example, with Todo, `list_todos` was only called when necessary, but you integrated `{list_todos()}` into the `instruction`, causing every request to inline all todos.

**2. Inlines tools directly within instructions is problematic for several reasons**

- Tracking tools is difficult, and their accessibility is not guaranteed.
- Running tools to generate data significantly increases processing time.
- You can't control the size of the generated data. It could be extremely large and even exceed the context window of the LLM.

**3. Unnecessary flexibility**

The biggest feature of this proposal is flexibility. You can put anything you want into the instruction, but this is exactly the taboo in design of the `instruciton`.

The `instruction` will work with session.  It needs to remain stable to a certain degree.

Data such as `{get_time()}` `{list_todos()}` may change at any time, thus interfering with LLM generating a response.

## Better Solution

The industry usually uses variables to solve this problem, and AIChat adopts the same approach.

```yaml
instructions: |
  You are interacting with the user: {user_id}
variables:
  - name: user_id
    description: The user id
```

When the agent is used for the first time, AIChat will prompt the user to set a user ID.
