### ISSUE TITLE
Support Baichuan Model

### ISSUE THREAD

**Issue by liukaizheng** [sigoden/aichat#702]
### Please confirm whether the following requirements are met:

- [y] Must have a REST/HTTP API.
- [y] Must be publicly accessible. It cannot require application review or have regional restrictions. A beta version is acceptable.
- [y] Must not act as an agent or proxy for other platforms.

### Please provide the following documents or links:

- API Documentation  https://platform.baichuan-ai.com/docs/api

**Comment by sigoden** [comment]
We are not planning to add new client for this platform.

But users can access bichuan through the `openai-compatible` client:

```yaml
  - type: openai-compatible
    name: bichuan
    api_base: https://api.baichuan-ai.com/v1
    api_key: <your-api-key>
    models:
      - name: Baichuan4
        max_input_tokens: 32768
        supports_function_calling: true


```
