### ISSUE TITLE
Document what models are good for RAG.

### ISSUE THREAD

**Issue by 0x0f0f0f** [sigoden/aichat#725]
I'm trying it out locally on my laptop with a RTX3060 6GB. Small 7B models work perfectly with Ollama for chat. I yet have to try RAG. Can you please add a paragraph to the wiki stating what models work well at the moment for RAG embeddings?

**Comment by 0x0f0f0f** [comment]
Ah nice! It didn't show this prompt when running `.rag some-name`

**Comment by 0x0f0f0f** [comment]
```
Welcome to aichat 0.19.0
Type ".help" for additional help.
> .rag
No available embedding model
```

**Comment by 0x0f0f0f** [comment]
Any embedding model I could run with Ollama and add to yaml config?

**Comment by sigoden** [comment]
Please search ollama library and add manually.

**Comment by 0x0f0f0f** [comment]
This should work well. https://ollama.com/library/mxbai-embed-large Thanks.

**Comment by 0x0f0f0f** [comment]
@sigoden I get 
```
Select embedding model: ollama:mxbai-embed-large
Invalid embedding model 'ollama:mxbai-embed-large'
```

This is my config
```
model: ollama
rag_embedding_model: ollama:mxbai-embed-large
clients:
- type: ollama
  api_base: http://127.0.0.1:11434
  api_auth: null
  models:
  - name: gemma2
    max_input_tokens: null
  - name: llama3
    max_input_tokens: null
  - name: mxbai-embed-large
    max_input_tokens: null
```

Am I missing anything?
