### ISSUE TITLE
Issues with ollama models

### ISSUE THREAD

**Issue by vlisivka** [sigoden/aichat#734]
config.yaml

```
clients:
- type: ollama
  api_base: http://127.0.0.1:11434
  api_auth: null
  models:
  - name: aya:latest
    max_input_tokens: 8192
  - name: codestral:latest
    max_input_tokens: 32768
```

roles.yaml
```
- name: code
  model: "ollama:codestral:latest"
  prompt: |-
    Provide only code without comments or explanations.
```

*Bug:*

```
$ aichat -r code <large-file
Failed to call chat-completions api

Caused by:
    Exceed max_input_tokens limit, total tokens: 8624, max_input_tokens: 8192, model: aya:latest.

```

*Expected:*  file should be passed on.

*Workaround:*

make codestral model first in the list, so it will be used instead.

Making it default via `model: "ollama:codestral:latest"` in config.yaml doesn't work too with error message:

```
Unknown client ''
```

**Comment by sigoden** [comment]
Cannot confirm the problem. 

It seems your configuration is messed up or didn't take effect.

Please paste the output of .info for further analysis.

```
> .info
```

```
> .role code
> .info
```

**Comment by vlisivka** [comment]
```
$ cargo run -- 
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.11s
     Running `/home/vlisivka/workspace/aichat/target/debug/aichat`
Welcome to aichat 0.19.0
Type ".help" for additional help.
> .info
model                   ollama:aya:latest
max_output_tokens       -
temperature             -
top_p                   -
dry_run                 false
save                    false
keybindings             emacs
wrap                    no
wrap_code               false
save_session            -
compress_threshold      4000
function_calling        false
use_tools               -
rag_reranker_model      -
rag_top_k               4
highlight               true
light_theme             false
config_file             /home/vlisivka/.config/aichat/config.yaml
roles_file              /home/vlisivka/.config/aichat/roles.yaml
env_file                /home/vlisivka/.config/aichat/.env
functions_dir           /home/vlisivka/.config/aichat/functions
agents_functions_dir    /home/vlisivka/.config/aichat/functions/agents
agents_config_dir       /home/vlisivka/.config/aichat/agents
rags_dir                /home/vlisivka/.config/aichat/rags
sessions_dir            /home/vlisivka/.config/aichat/sessions
messages_file           /home/vlisivka/.config/aichat/messages.md
log_path                /home/vlisivka/.config/aichat/aichat.log

> .role code

code> .info
model                   ollama:codestral:latest
max_output_tokens       -
temperature             -
top_p                   -
dry_run                 false
save                    false
keybindings             emacs
wrap                    no
wrap_code               false
save_session            -
compress_threshold      4000
function_calling        false
use_tools               -
rag_reranker_model      -
rag_top_k               4
highlight               true
light_theme             false
config_file             /home/vlisivka/.config/aichat/config.yaml
roles_file              /home/vlisivka/.config/aichat/roles.yaml
env_file                /home/vlisivka/.config/aichat/.env
functions_dir           /home/vlisivka/.config/aichat/functions
agents_functions_dir    /home/vlisivka/.config/aichat/functions/agents
agents_config_dir       /home/vlisivka/.config/aichat/agents
rags_dir                /home/vlisivka/.config/aichat/rags
sessions_dir            /home/vlisivka/.config/aichat/sessions
messages_file           /home/vlisivka/.config/aichat/messages.md
log_path                /home/vlisivka/.config/aichat/aichat.log
```

**Comment by sigoden** [comment]
From your pasted material, it seems that aichat has loaded the model correctly, so the problem you mentioned is impossible to happen.

**Comment by sigoden** [comment]
Can you provide a screenshot of the tabcompletion for .model? I'd like to see if the model parameter is set correctly.

```
.model ollama:<tab>
```

**Comment by vlisivka** [comment]
```
$ cargo run -- 
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.13s
     Running `/home/vlisivka/workspace/aichat/target/debug/aichat`
Welcome to aichat 0.19.0
Type ".help" for additional help.
> | .model ollama:
ollama:aya:latest            8192 /        -  |       - /      -        
ollama:codestral:latest     32768 /        -  |       - /      -        
```

**Comment by sigoden** [comment]
Everything looks normal.

Have you tried `aichat -r code <large-file` again? Is there still an error?

**Comment by vlisivka** [comment]
Yes, problem persist:

```
$ cargo run -- -r code <~/workspace/translations/net-tools/net-tools.po 
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.12s
     Running `/home/vlisivka/workspace/aichat/target/debug/aichat -r code`
Failed to call chat-completions api

Caused by:
    Exceed max_input_tokens limit, total tokens: 8624, max_input_tokens: 8192, model: aya:latest.
```

When I switched models:
```
clients:
- type: ollama
  api_base: http://127.0.0.1:11434
  api_auth: null
  models:
  - name: codestral:latest
    max_input_tokens: 32768
  - name: aya:latest
    max_input_tokens: 8192
```

then error changed to:

```
$ cargo run -- -r code <~/workspace/translations/net-tools/net-tools.po 
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.32s
     Running `/home/vlisivka/workspace/aichat/target/debug/aichat -r code`
Unknown client ''
```

When I added default `model: ollama:codestral` (without :latest) to config:
```
model: ollama:codestral
clients:
- type: ollama
  api_base: http://127.0.0.1:11434
  api_auth: null
  models:
  - name: codestral:latest
    max_input_tokens: 32768
  - name: aya:latest
    max_input_tokens: 8192
```

it starts to work:

```
$ ollama ps
NAME            	ID          	SIZE 	PROCESSOR	UNTIL                   
codestral:latest	fcc0019dcee9	15 GB	100% GPU 	About a minute from now	
```

I use Fedora 40 with ollama 0.2.5.
