### ISSUE TITLE
Error Please enable function calling before using the agent

### ISSUE THREAD

**Issue by amolkhatri** [sigoden/aichat#809]
**Describe the bug**
Not able to run the agent. Its failing with "Please enable function calling before using the agent." My config is as follow

```
model: openai
function_calling: true
clients:
- type: openai
  api_key: <My api key>
  supports_function_calling: true


```
command I am running

`
.agent todo
`
