### ISSUE TITLE
Compatibility with Cerebras API

### ISSUE THREAD

**Issue by hellmind** [sigoden/aichat#829]
Hello everyone,

I am exploring the possibility of integrating AIChat with the Cerebras API and was wondering if anyone has already tested this combination. Specifically, I'm curious if there are any known issues or additional configurations required to get AIChat to function correctly with Cerebras.

If you've tried this setup, I would greatly appreciate your insights on performance, compatibility, and any tips on how to get it running smoothly.

Thanks in advance for sharing your experience!

Sample:(that doesnt works)

  - type: openai-compatible
    name: cerebras
    api_base: https://api.cerebras.ai/v1
    api_key: csk-ddcf584vy49xh4wp9y93djwv9twm5d6wvfec4xxmcyv3pw6

**Comment by sigoden** [comment]
We will not officially support this platform.

You can add it manaully
```
  - type: openai-compatible
    name: cerebras
    api_base: https://api.cerebras.ai/v1
    api_key: xxx
    models:
      - name: llama3.1-8b
        max_input_tokens: 8192
      - name: llama3.1-70b
        max_input_tokens: 8192
```
