### ISSUE TITLE
Failed to call chat-completions API Cause by max_tokens: Field required

### ISSUE THREAD

**Issue by jeanlucthumm** [sigoden/aichat#872]
```
Welcome to aichat 0.21.1
Type ".help" for additional help.
> test
Failed to call chat-completions api

Caused by:
    max_tokens: Field required (type: invalid_request_error)
```

Contents of `.config/aichat/config.yml`:

```yml
model: claude:claude-3-5-sonnet-20240620
highlight: true
light_theme: true
clients:
- type: claude
  api_key: [redacted]
  models:
    - name: claude-3-5-sonnet-20240620
      max_input_tokens: 200000
      pass_max_tokens: 4096
      require_max_tokens: true
      input_price: 3
      output_price: 15
      supports_vision: true
      supports_function_calling: true
```

I've also tried `max_tokens` instead of `max_input_tokens` but did not work

**Comment by sigoden** [comment]
You don't need to manually add models for the `claude` client. 

If you do want custom models, check the following:

https://github.com/sigoden/aichat/blob/beaf5946a98f1552763ff974942cc71ee531fe62/models.yaml#L120-L129

**Comment by kyu08** [comment]
Hi @sigoden ,
Thanks for maintaining aichat always!
Could you show me how can I fix this error? 🙇‍♂️

![Image](https://github.com/user-attachments/assets/966e1ed0-0afd-482c-b583-3fc2c9ea9164)

## A part of config file
```yaml
model: claude:claude-3-7-sonnet-20250219      # LLM model
temperature: 1.0                 # LLM temperature
save: true                       # Whether to save the message
save_session: true               # Whether to save the session, if null, asking
highlight: true                  # Set false to turn highlight
light_theme: false               # Whether to use a light theme
wrap: no                         # Specify the text-wrapping mode (no, auto, <max-width>)
wrap_code: false                 # Whether wrap code block
ctrlc_exit: true                # Whether to exit REPL when Ctrl+C is pressed
keybindings: vi               # REPL keybindings. (emacs, vi)
prelude: ''                      # Set a default role or session (role:<name>, session:<name>)
```

Above error message is not shown when I specify `model: claude:claude-3-5-sonnet-latest`.

## What I tried
- specify `max_tokens` on top level of config file
- specify `max_tokens` within `- type: claude`

The results were same.

Thank you.
