### ISSUE TITLE
Patch query params in config file

### ISSUE THREAD

**Issue by osintalex** [sigoden/aichat#890]
**Is your feature request related to a problem? Please describe.**

Nice project! Ran into some issues setting this up for Azure OpenAI where I needed to send the api version as a query param since the default one wouldn't work. 
**Describe the solution you'd like**

Would like to be able to patch query parameters similar to how you can patch request headers
**Describe alternatives you've considered**

I've hardcoded the url I want for chat completions but this feels inelegant and contrarian to the design of the config file.
**Additional context**

Happy to send in a PR for this if that helps.

**Comment by sigoden** [comment]
We will not support this feature. please patch the url instead.

```
  patch:
    chat_completions:
      'gpt-4o':
        url: https://{RESOURCE}.openai.azure.com/openai/deployments/{NAME}/chat/completions?api-version={VERSION}
```
