### ISSUE TITLE
[RAG] About Executing JS before indexing url ? 

### ISSUE THREAD

**Issue by dtrckd** [sigoden/aichat#919]
Hi,

Would you have any suggestion to handle URLs that need to execute Javascript to be rendered ?

**Comment by sigoden** [comment]
There is no chance for AIChat to natively support this feature. However, users can use `document_loaders` with custom tools to achieve the goal.


```yaml
document_loaders:
    url: curl -o $2 'https://r.jina.ai/$1'
    recursive_url: my-crawler -o $2 $1
```
