### ISSUE TITLE
automatic session creation and management using aichat's existing YAML infrastructure

### ISSUE THREAD

**Issue by garyblankenship** [sigoden/aichat#997]
**Is your feature request related to a problem? Please describe.**
Currently in aichat:
- Sessions must be explicitly created with `-s` flag
- Users often forget to start sessions and lose valuable conversations
- No automatic preservation of chat history
- Manual session management interrupts natural workflow
- Valuable context and solutions are lost when sessions aren't explicitly created

**Describe the solution you'd like**

1. Automatic Session Management:
- Create sessions automatically for every chat interaction
- Use meaningful default naming (e.g., `YYYYMMDD_HHMMSS_context`)
- Preserve working directory context in session metadata
- Allow session merging for related conversations

2. Configuration in config.yaml:
```yaml
sessions:
  auto_create: true              # Enable automatic sessions (default: true)
  name_format: "{date}_{time}"   # Custom naming pattern
  base_path: ~/.config/aichat/sessions
  retention_days: 90             # Auto-cleanup old sessions
  context_capture:               # What context to include
    working_directory: true      # Include pwd in session name/metadata
    git_repo: true              # Include repo name if in git directory
```

3. Enhanced CLI Commands:
```bash
# List recent sessions
aichat sessions list --last=24h

# Search across sessions
aichat sessions search "kubernetes"

# Merge related sessions
aichat sessions merge session1 session2

# Clean up old sessions
aichat sessions cleanup --older-than=90d
```

4. Features:
- Zero-configuration session logging
- Intelligent session naming based on context
- Session search and management tools
- Automatic cleanup of old sessions
- Session merging for related conversations

**Describe alternatives you've considered**
1. Current manual session management: Requires explicit user action
2. Always-on single session: Would become too large
3. Time-based session rotation: Might split related conversations

**Additional context**
This would:
- Preserve all conversations by default
- Maintain existing YAML format for compatibility
- Require no change in normal usage
- Make session management invisible to users
- Enable easy access to chat history
